language: java
sudo: false
before_install:
    cd ./devonfw-guide/
script: 
  - jdk_switcher use openjdk8
  - mvn clean package -Ddocgen.images.dir=images,documentation -P !custom-style,generate-html-doc