language: java
sudo: false
jdk:
  - openjdk8
before_install:
  - cd ./devonfw-guide/
script: 
  - mvn clean package -Ddocgen.images.dir=images,documentation -P !custom-style,generate-html-doc
deploy:
    provider: pages
    skip_cleanup: true
    # github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: ./target/asciidoc/
    on:
        branch: develop