language: java
sudo: false
jdk:
- openjdk8
env:
  global:
    secure: QSLYJ4Bnldt+HmR4ZuEfYdXp9BMpNIT5vaKZwcCSjW3ePJufIDYMODNY9u2sqmGX21guq8G82sa8ogSkaO/GGBcS4dI07Sypg6k9m36BrEK36YSHw5yk3S0S4YFeq4D9nxmHf7w3qP44o2i73l+2i1z2+6JE0OYfcPzHt2EIQdXluM6cLPyIBhHJn95zWrNgD6gprEJqxANEJKrFQEcM4gNMdmAFzuWWwL2T5gh0qcubo+6a+hkvtYOvm5KBrxtcxjQl8pxbyOilZzjh79+eOF+iLgS5JGKmQOPYUWsSNBHVmtUWEzQrP2yhtK6vBKLBxxXWXH/QmWOIA86+8F5YAWL44ibLqLVl8rXtyO8OmuXDrQBjYtDo8gTFO6ShyvST0BVZHpgWOHM9S3SW6BCU2ORenhoQZMCnWjaCIWx3ucWZOef48qlfGEtojbTM/u7ZXLlYA9otkx9gsKmcYRzwD7+35ZvWqRYnZl4n4UGfQpMKLN7ia5SeXHpaLwMA9NU9MUnw3oezhm7NXF/nXpbuQ4ZJl/ShnCCRBZDig/cjUoz4N+gxFk+38xaMg9+Nf9R0YjnN/CYp7wIr6wQrenZ1GQ1DHOZEEdUooQngstQGCzaZRk4yq7oDUZJR//I5YIUaxBi8K6lDvT9uPHJUexEgu1zk3MFhYYsaM0+j8OGpZeU=
before_install:
- cd ./devonfw-guide/
script:
- mvn clean package -Ddocgen.images.dir=images,documentation -P !custom-style,generate-html-doc
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: "./target/asciidoc/"
  on:
    branch: develop