name: build-and-deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: SetupRuby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      
      - name: Setup Node
        uses: actions/setup-node@v1
      
      - name: InstallAsciidoctorGem
        run: gem install asciidoctor -v 1.5.7.1

      - name: Build
        run: mvn clean package -Doutput.format=html
        
      - name: SplitHtml
        run: |
          asciidoctor -r ./asciidoctor-extensions/multipage-html5-converter.rb -b  multipage_html5 ./target/asciidoc/devonfw-guide/master.asciidoc -a toc=left -D ./target/generated-docs/website/pages/docs
          ls -l target/generated-docs/website/pages/docs
          
      - name: AddHeaderToSplittedHtml
        run: |
          cd merge-header
          npm install
          node merger.js ./target/generated-docs/devonfw-guide/master.html ../target/generated-docs/devonfw-guide/website/pages/docs/ ../target/generated-docs/devonfw-guide/pages/docs/
          cd ..
          

      - name: Cleanup
        run: | 
          cd target/generated-docs
          rm -Rf asciidoctor* documentation pom.xml README.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.DEVONFW_CORE_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: target/generated-docs # The folder the action should deploy.
