name: build-and-deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: SetupRuby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      
      - name: InstallAsciidoctorGem
        run: gem install asciidoctor -v 1.5.7.1

      - name: Build
        run: mvn clean package -Doutput.format=html
        
      - name: SplitHtml
        run: |
          asciidoctor -r ./asciidoctor-extensions/multipage-html5-converter.rb -b  multipage_html5 ./target/asciidoc/devonfw-guide/master.asciidoc
          ls -l target/asciidoc/devonfw-guide/
          mkdir target/generated-docs/splitted-html
          cp ./target/asciidoc/devonfw-guide/*.html ./target/generated-docs/splitted-html
          ls -l target/generated-docs/splitted-html

      - name: Cleanup
        run: | 
          cd target/generated-docs
          rm -Rf asciidoctor* documentation pom.xml README.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.DEVONFW_CORE_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: target/generated-docs # The folder the action should deploy.
